name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - main # or 'master', whatever your main branch is
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Install dependencies
      - run: npm ci

      # 4. Build the Astro site
      - run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Astro output directory
          cname: gosferano.com
